sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t scottenriquez/docker-production-flow -f Dockerfile.dev .

script:
  - docker run -v /app/node_modules -v $(pwd):/app scottenriquez/docker-production-flow npm run test -- --coverage
