sudo: required
services:
  - docker

before_install:
  - docker build -t scottenriquez/docker-production-flow -f Dockerfile.dev .

script:
  - docker run scottenriquez/docker-production-flow npm run test -- --coverage
